[versions]
junit-jupiter = "5.10.2"
assertJ-version = "3.26.3"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJ-version" }
